"use strict";
/* One-off helper: localize Google Fonts.
   Downloads every woff2 subset referenced by the Google Fonts CSS
   into vendor/fonts/ and writes css/parts/fonts.css with local paths.
   Run from project root: node tools/download-fonts.js */

const fs = require("fs");
const path = require("path");

/* note: IBM Plex Sans TC is not served by the css2 API (returns 400),
   so the TC companion face is Noto Sans TC instead */
const CSS_URL =
  "https://fonts.googleapis.com/css2" +
  "?family=IBM+Plex+Mono:wght@400;500;600" +
  "&family=Noto+Sans+TC:wght@400;500;700" +
  "&display=swap";
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const ROOT = path.join(__dirname, "..");
const FONT_DIR = path.join(ROOT, "vendor", "fonts");
const OUT_CSS = path.join(ROOT, "css", "parts", "fonts.css");

async function main() {
  const res = await fetch(CSS_URL, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error("CSS download failed: " + res.status);
  let css = await res.text();

  fs.mkdirSync(FONT_DIR, { recursive: true });
  const urls = [...new Set(css.match(/https:\/\/fonts\.gstatic\.com\/[^)]+/g))];
  console.log("font files to download:", urls.length);

  let done = 0;
  const BATCH = 16;
  for (let i = 0; i < urls.length; i += BATCH) {
    const slice = urls.slice(i, i + BATCH);
    await Promise.all(
      slice.map(async (u) => {
        const name = u
          .split("/")
          .slice(-3)
          .join("-")
          .replace(/[^A-Za-z0-9_.-]/g, "");
        const buf = Buffer.from(await (await fetch(u)).arrayBuffer());
        fs.writeFileSync(path.join(FONT_DIR, name), buf);
        css = css.split(u).join("../../vendor/fonts/" + name);
        done++;
      })
    );
    process.stdout.write("\rdownloaded " + done + "/" + urls.length);
  }

  const header =
    "/* ============================================================\n" +
    "   Local fonts: IBM Plex Sans TC + IBM Plex Mono.\n" +
    "   Generated by tools/download-fonts.js — do not edit by hand.\n" +
    "   ============================================================ */\n\n";
  fs.writeFileSync(OUT_CSS, header + css);
  console.log("\nwrote", path.relative(ROOT, OUT_CSS));
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
